glideapps/quicktype

src/Doc.purs
src/IR.purs
src/IRGraph.purs
src/Language/CSharp.purs
src/Language/Elm.purs
src/Language/Golang.purs
src/Language/Java.purs
src/Language/JsonSchema.purs
src/Language/SimpleTypes.purs
src/Language/Swift.purs
src/Language/TypeScript.purs
src/Main.purs
src/Transformations.purs

Split IRAnything into IRNoInformation and IRAnyType

---

.vscode/extensions.json
.vscode/settings.json
README.md
package-lock.json
package.json
test/lib/deepEquals.ts
test/lib/multicore.ts
test/test.ts
test/tslint.json

* Adds VSCode extension recommendations to the workspace, notably adding `prettier` which formats `.ts` files on save.
* Adds a workspace preference to format files on save.
* Reformat `.ts` files.
* Add `tslint` for TypeScript style checking and fix the warnings it reported

TypeScript refinements for `test/`

---

src/Language/CSharp.purs
test/fixtures/csharp/Program.cs

Fixes #26 
```csharp
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KitchenSink;
//
//    KitchenSink data = KitchenSink.FromJson(jsonString);
//
namespace KitchenSink
{
using System;
using System.Net;
using System.Collections.Generic;
using Newtonsoft.Json;
public partial class KitchenSink
{
[JsonProperty("doubleValue")]
public double DoubleValue { get; set; }
[JsonProperty("nullValue")]
public object NullValue { get; set; }
[JsonProperty("dateValue")]
public string DateValue { get; set; }
[JsonProperty("booleanValue")]
public bool BooleanValue { get; set; }
[JsonProperty("differentThings")]
public DifferentThings[] DifferentThings { get; set; }
[JsonProperty("mapValue")]
public Dictionary<string, long> MapValue { get; set; }
[JsonProperty("intValue")] …
```

Adds FromJson and ToJson methods to top-levels

---

src/Language/CSharp.purs

Allows us to support Unity but not look too old-fashioned otherwise!
We'll also use this to enable C# 7.0 tuple syntax when we implement #48.

Option to choose between C# 5 and 6

---

cli/either.ts
cli/quicktype.ts
cli/tsconfig.json
test/fixtures.ts
test/languages.ts
test/lib/multicore.ts
test/test.ts
test/tsconfig.json
test/utils.ts

I fixed all our code to work with strict null checks
(might have caught one or two unproblematic bugs),
but I don't know how to configure it such that only
our code, and not imported modules, are compiled
with strict null checks.  At least one module doesn't
compile.

Trying to enable TypeScript strict null checks

---

package.json
src-ts/quicktype.ts
test/inputs/spotify-api/Album/She's So Unusual.json
test/inputs/spotify-api/Album/The Best of Keane (Deluxe Edition).json
test/inputs/spotify-api/Artist.json
test/inputs/spotify-api/Playlist.json
test/inputs/spotify-api/Track.json
test/inputs/spotify-api/UserProfile.json

Allow reading from directories of sample data containing many top-levels

---

src-ts/ConvenienceRenderer.ts
src-ts/Language/All.ts
src-ts/Language/CPlusPlus.ts
src-ts/Language/Golang.ts
src-ts/Language/Swift.ts
src-ts/Support.ts
src-ts/TargetLanguage.ts
src-ts/Type.ts
src/Language/Swift.purs
test/fixtures.ts
test/languages.ts

This leaves us with Swift 3 in PureScript and Swift 4 in TypeScript.

Swift in typescript

---

package.json
src-ts/Type.ts
test/inputs/json/priority/recursive.json
test/languages.ts

Hashing and equality were recursive and would
potentially overflow the stack.

Kinda fix recursive types

---

src-ts/TargetLanguage.ts
src-ts/quicktype.ts
src/Config.d.ts
src/Config.purs
src/Main.purs

This is useful when we want to time or profile individual steps.

Allow disabling combining classes and rendering

---

src/Language/TypeScript.ts

Typescript enum support

---

package-lock.json
package.json
src/get-stream/buffer-stream.ts
src/get-stream/index.ts
src/get-stream/license
src/index.ts

Fixes https://github.com/sindresorhus/get-stream/issues/20

Incorporate get-stream to keep quicktype on ES5

---

src/Inference.ts

The value array optimization made this stop working, because we
can't just count the number of array elements anymore, since they
might contain more arrays.

Fix enum inference

---

.travis.yml

* Include ci:skip-tests in a commit message to skip CI tests.

Allow skipping CI tests, and auto-patch npm version

---

src/Type.ts
src/TypeBuilder.ts

Previously, a forwarding type ref didn't have an index until
it was resolved when the type it stood for was finished building.
If it was part of a recursive type it could end up in a set or map
before it was finished building, and then it would dereferenced,
which would panic.
This change will create an index for a forwarding type ref in
case it was dereferenced, and we try to make whoever builds the
type use that index.  It could happen that it wants to reuse an
existing type, however, in which case we'll still panic.

Make rewriting recursive types less brittle

---

src/Type.ts
src/TypeBuilder.ts

This way we don't have to pass through the
forwarding reference, and other stuff in the
future.

Use a helper class to create types in Type.map

---

src/Language/Golang.ts
src/TargetLanguage.ts
src/index.ts

We need this for the plug-ins.

Make indentation configuration in Options

---

src/Language/Objective-C.ts
src/Source.ts
test/fixtures/objective-c/QTTopLevel.h

* Minimize NSNull* functions
* Minimize extensions to NSDictionary with objectForKey:withClass:
* 'pseudo' enums

Objective-C improvements

---

src/Language/Objective-C.ts

* Prevent throw collision #446 
* Also fixes #445

Prevent throw collision

---

package.json
src/Language/Swift.ts
test/fixtures/swift/main.swift

Allow convenience initializers and serializers to throw

---

src/Language/Swift.ts
test/fixtures/swift/SwiftFixture.xcodeproj/project.pbxproj
test/fixtures/swift/main.swift
test/fixtures/swift/quicktype.swift

Also updates Swift fixture with an Xcode project for debugging

Omit unneeded failable initializers

---

package.json
src/Language/Objective-C.ts

* More boolean prefixes
* More consistent method style

Objective-C Small Fixes

---

src/Language/Rust.ts

Added type descriptions and class property descriptions,  https://github.com/quicktype/quicktype/issues/521.

Emit descriptions in RustRenderer.

---

src/Language/Rust.ts

Ref https://github.com/quicktype/quicktype/issues/516

Header comment compacted, fix invalid JSON in header

---

test/.prettierrc
test/buildkite.ts
test/fixtures.ts
test/languages.ts
test/test.ts

CI with Buildkite

---

src/Language/CSharp.ts

Emit descriptions in C#

---

.gitignore
Dockerfile
test/fixtures/java/src/main/java/io/quicktype/Converter.java
test/fixtures/java/src/main/java/io/quicktype/TopLevel.java
test/fixtures/rust/Cargo.toml
test/languages.ts

Massive test speedups for Rust, Elm, and Java

---

.buildkite/build-pr.sh
.buildkite/pipeline.yml

* Puts Buildkite pipeline spec in repo
* Tests merge commit if we're building a PR

Put Buildkite pipeline spec in repo

---

src/Language/CSharp.ts

…mezone is specified.
Ref https://github.com/quicktype/quicktype/issues/502

DateTime serialization and deserialization uses UTC if no timezone specified

---

src/Language/CPlusPlus.ts

The option can be used like `--namespace a::b::c`

Support nested namespaces in C++

---

src/Inference.ts
src/TypeBuilder.ts
src/UnifyClasses.ts

This will make UnionBuilder reusable for taking input from the
resolver of an intersection type.

Factor out the provider of constituent types for UnionBuilder

---

src/Language/Swift.ts

Terser labels for options in Swift

---

src/Inference.ts
src/index.ts

Commit b31ed07e4b6418389d33094bc15ed2ee5a356aa2

Revert fixed-top-level.

---

src/Language/Swift.ts

fixed, im closing the previous PR to prevent multiple commits.

Improved horizontal rule in swift comment syntax

---

src/ConvenienceRenderer.ts
src/Language/Ruby/index.ts

* Omit synthetic StrictDouble when not used
* Align enum declarations

Tidier Types module

---

src/cli.ts

Only show and process the target languages they select.

Improve CLI for API users

---

src/cli/index.ts

Avoids the 'no input file' error

Take care not to proceed when user is just setting telemetry

---

src/cli/index.ts

Rename postman-json to postman.

---

src/Language/CSharp.ts

The magic sauce:
https://github.com/json-helpers/quicktype/blob/emit-superclass/src/Language/CSharp.ts#L271

Emit superclass - needs testing and review

---

src/Language/Swift.ts
test/languages.ts

(I'll squash these commits)
Fixes #430

Allow specifying access level (internal or public) in Swift

---

src/ConvenienceRenderer.ts
src/Language/JavaScript.ts
src/Language/TypeScriptFlow.ts

Unify object type representation, and make a general
reference "type" so we can represent all kinds of cycles
later on.

Full object support for JS languages.  Fixes #764

---

package.json

Otherwise we can't reproduce builds.

Refer to an explicit typescript-json-schema commit

---

src/Language/CSharp.ts

Use DateTimeOffset unqualified in C#

---

src/Language/Swift.ts
test/languages.ts

This is the Foundation way to download data (no dependencies).

URLSession task extensions for Swift

---

src/InferEnums.ts

Don't make an enum if all cases are number strings

---

script/watch

Fixed incorrect casing

---

src/language/CPlusPlus.ts

Changed code generation methods in CPlusPlus.ts from `private` to `protected` to enable to make them overridable.
Added a function in CPlusPlus.ts named emitClassMembers to emit the contents of a class.

Improve C++ Target Language Extendability

---

src/quicktype-core/RendererOptions.ts

@schani wanted me to commit this (he provided the change on Slack). I just wanted to give him credit!

Fixed handling of undefined option values

---

build/quicktype-core/package.in.json
src/quicktype-core/language/CSharp.ts

@dvdsgl how is it now?
Reference: https://quicktype.slack.com/archives/C68E91E8J/p1528493269000348

Style changes for the base class option

---

script/build.ts

Problem:
https://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-for-awk-with-a-shebang-i-e
Solution:
http://sambal.org/2014/02/passing-options-node-shebang-line/

Fix the CLI on Linux.  Fixes #940

---

script/build.ts

See https://github.com/quicktype/quicktype/pull/941

Use straightforward hash-bang with /usr/bin/env to fix Windows CLI

---

src/quicktype-core/Transformers.ts

We had dead code for encoders of unions of integers,
stringified integers, and something else, because we
superfluously checked the integer member twice.  Now
we do the same as other cases, which is just pick the
simplest one.

Filter superfluous member matches in choices

---

src/quicktype-core/language/Swift.ts

* Explicit initializers for public structs (fixes #899)
* `.with` mutator methods (fixes #900)

Swift enhancements

---

.gitignore
src/quicktype-core/language/CSharp.ts

#975 Implementing implicit operator for c#

---

build/quicktype-core/package.in.json
package.json

Add `wordwrap` to dependencies

---

.buildkite/pipeline.yml

The tests fail with a supposed compiler bug very often.

Don't test Crystal

---

src/quicktype-core/language/JavaScript.ts
src/quicktype-core/language/TypeScriptFlow.ts
test/languages.ts

Fixes #1118
I am not sure, if I need to add some more tests. If so, kindly advice were to add them.

feat: add JavaScript option for Acronym Style

---

src/quicktype-core/language/JavaScript.ts
src/quicktype-core/language/TypeScriptFlow.ts
test/languages.ts

I tried to mimic the Python implementation where possible.
Related to #316.

Add date-time support for JavaScript and TypeScript

---

src/quicktype-core/language/Java.ts
test/languages.ts

Java: Option to "Use T[] or List<T>" (similar to C#)

---

src/quicktype-core/language/Java.ts

First attempt for to fix #1162. Without unittest for now.

Feature/java missing imports when using  just types #1162

---

src/quicktype-core/language/CPlusPlus.ts

Wrapped the optional type helpers in an include guard, since they're in a fixed namespace.
Previously these types caused conflicts when trying to include multiple generated code files, as they were exactly identical, even when namespaces differs. Now, they will only be included once, regardless of how many code files are included.

Wrap function definitions in a fixed namespace with include guards

---

src/quicktype-core/language/Swift.ts

- We do not have a way to disable these warnings, so this is just being nice and silencing them.

Fix Swift 5 compiler warnings

---

src/quicktype-core/language/Swift.ts

https://github.com/quicktype/quicktype/pull/1218 added the ability to add default values to swift code by following the strategy proposed in [this tutorial](https://blog.quicktype.io/customizing-quicktype/).  With that came the need to modify how `quicktype` renders the `init` method of a type because a `let`(inmutable value) can't be initialized twice or the compiler will throw an error.
This PR aims to allow `quicktype-core` users to customize a type's `init` by defining the set of properties that has to be rendered. (Instead of all of them).
I've added a `initializableProperties` method which is basically a wrapper  for `forEachClassProperty` method to be used inside the `renderClassDefinition` method when rendering a type's `init`
Additionally I've defined a new ~class~ interface …

Allow for swift's init customization

---

src/cli/index.ts

Fix source URLs CLI option

---

src/cli/NodeIO.ts
src/cli/index.ts

Observe HTTP headers for all requests

---

src/quicktype-core/language/Swift.ts

I added a option to generate mutable user properties for Swift classes or structs.

Add option for mutable object properties.

---

script/dev.ps1

This builds and runs the image on windows. Having some issuses still.

Powershell script to make docker image

---

Dockerfile

This appears to fix our CI, which has been broken for a few months.

Fix Python PPA

---

package-lock.json
package.json
src/quicktype-core/index.ts
src/quicktype-core/input/JSONSchemaInput.ts

Need this type for programmatically using quicktype in https://github.com/untitaker/quicktype-markdown

Fix build issues and missing exports around quicktype-core

---

README.md

Update README.md slack url

---

README.md
src/quicktype-core/index.ts
src/quicktype-core/language/All.ts
src/quicktype-core/language/JavaScriptPropTypes.ts
test/fixtures.ts
test/fixtures/javascript-prop-types/main.js
test/fixtures/javascript-prop-types/package-lock.json
test/fixtures/javascript-prop-types/package.json
test/languages.ts

This PR adds a very basic [prop-types](https://www.npmjs.com/package/prop-types) renderer.
```typescript
interface PrimitiveObject {
string: string;
bool: boolean;
float: number;
union: string | boolean | number;
object: object
}
interface PrimitiveArrayObject {
strings: string[];
bools: boolean[];
floats: number[];
unions: string[] | boolean[] | number[];
objects: object[];
}
interface CompositeObject {
primitive: PrimitiveObject;
primitiveArrays: PrimitiveArrayObject;
}
```
Emits:
```javascript
// For use with proptypes.
import PropTypes from 'prop-types';
export const CompositeObject = PropTypes.shape({
primitive: PrimitiveObject,
primitiveArrays: PrimitiveArrayObject,
});
export const PrimitiveObject = PropTypes.shape({
bool: PropTypes.bool.isRequired,
float: …
```

Prop-Types Support

---

src/quicktype-core/language/CSharp.ts
src/quicktype-core/language/Golang.ts

- Added `just-types-and-namespace` to C# renderer.
- Added `just-types-and-package` to Go renderer.

Just types and package/namespace

---

src/quicktype-core/language/Java.ts
test/fixtures/java-lombok/src/main/java/io/quicktype/Converter.java
test/fixtures/java/src/main/java/io/quicktype/Converter.java

Java - Fix deprecation in jackson converter code

---

script/test

Environmental variable fix for UTC timezone in unit tests

---

README.md

README for Haskell feature
- target languages
- test dependencies

readme for haskell

---

src/quicktype-core/language/Dart.ts

Dart constructors first

---

src/.prettierrc
src/quicktype-core/language/Dart.ts

Use method names fromMap() & toMap()

---

src/quicktype-core/language/Rust.ts

Add edition 2018 style use sedre rather than extern crate

---

build/quicktype-core/package-lock.json
build/quicktype-core/package.in.json

Close #1502
This PR also updates `build/quicktype-core/package-lock.json` by runnnig `npm update`.

Add 'is-url' in dependencies of quicktype-core

---

src/cli/TypeSource.ts

Fixed the correct relative module path reference for import from quicktype-core

Fix for import reference module path

---

src/quicktype-core/index.ts

dart support is much needed for quick type as flutter is on the rise

added dart related export at index.ts

---

src/quicktype-core/language/Dart.ts

Added documentation to generated class properties if available (for example with a JSON Schema) and an option to generate annotations for the Hive package

[Dart] Documentation for class properties and support for the Hive package

---

src/quicktype-core/language/Dart.ts

I hope this should do the trick for freezed in #1673.
I wasn't able to test, because `npm install` failed. I'm not spending more time on this. Someone please take over.

Update dart / freezed code generation UNTESTED

---

build/build-utils.js

build-utils: add missing LICENSE

---

src/quicktype-core/language/CSharp.ts

Hello everybody,
I've added an option at the C# generator to make all properties virtual, so you can extend them on subclasses!
Enjoy! 😊

C#: Add virtual Property Switch

---

src/quicktype-core/index.ts

Looks like I need this options object in order to subclass the cpp renderer.

Export cPlusPlusOptions

---

src/quicktype-core/language/TypeScriptFlow.ts

Reverted constructor changes and rebased onto master

TypeScript renderer: Option to render unions insted of enums

---

.github/workflows/test-pr.yaml

More action work

---

src/quicktype-core/language/Rust.ts

Fix type name in comment

---

.github/workflows/test-pr.yaml
.vscode/settings.json
src/quicktype-core/language/ruby/index.ts
src/quicktype-core/language/ruby/keywords.ts
test/fixtures.ts
test/fixtures/ruby/.bundle/config
test/fixtures/ruby/Gemfile.lock
test/languages.ts

* Incorporates work from #1385
* Fixes #1379

Working Ruby fixture

---

src/quicktype-core/language/Dart.ts
test/languages.ts

fix https://app.quicktype.io/ Dart Null Safety Option

Expose Dart Null Safety Option

---

FAQ.md

Add new `quicktypePropertyOrder` FAQ to index (#2129)

---

packages/quicktype-core/src/language/TypeScriptFlow.ts
test/languages.ts

add `prefer-types` option for typescript

---

README.md

See https://github.com/quicktype/quicktype/pull/1616#issuecomment-1374890759

Add PHP as target option

---

.github/workflows/test-pr.yaml
.gitignore
package-lock.json
package.json
packages/quicktype-core/src/language/Java.ts
script/test
test/fixtures.ts
test/fixtures/java-lombok/pom.xml
test/fixtures/java-record/pom.xml
test/fixtures/java-record/src/main/java/io/quicktype/App.java
test/fixtures/java-record/src/main/java/io/quicktype/Converter.java
test/fixtures/java-record/src/main/java/io/quicktype/TopLevel.java
test/fixtures/java/pom.xml
test/languages.ts

Add support for Java Records (JEP 395)

---

packages/quicktype-core/src/language/Python.ts

I got tired of manually fixing results of this, so I fixed the bug instead.
"= None" string can only be added to root-level definitions in Pythons. Refer to #2020 for further detail.
closes #2020

[Python] Fix typedefs with Optional adding "= None" to non-root level def

---

packages/quicktype-core/src/language/CPlusPlus.ts

fix typo for optionalMacroName

fix typo for optionalMacroName  at CPlusPlus.ts

---

packages/quicktype-core/src/language/Rust.ts

This PR adds a new option for exporting to rust that allows for deriving clone automatically.
Closes #2200

Added derive Clone support for rust (#2200)

---

packages/quicktype-core/src/language/CPlusPlus.ts

The generated code doesn't compile without this. Please review my changes because this is my first 5 minutes in this codebase :sweat_smile:

add missing optional header

---

packages/quicktype-core/src/language/Dart.ts

The following issues existed with Code Generation for Dart :
1. Constructor would be mentioned before the variable declarations.
2. The Copy Constructor generator didn't include params as nullables.
This pull request fixes these issues.
Also refactored the Dart code generation code.

Fix : Dart Code Gen Errors

---

packages/quicktype-core/src/language/Dart.ts

[json_annotation](https://pub.dev/packages/json_annotation) is a very popular Dart package that provides annotations and code generation capabilities for JSON serialization and deserialization by [json_serializable](https://pub.dev/packages/json_serializable)
I hope it would be very useful addition for Flutter community. Please add this option to the website as well, and let me know if any changes are required.

feat: Add support for json_annotation in Dart

---

packages/quicktype-core/src/language/Dart.ts

This is in reference to issue: https://github.com/quicktype/quicktype/issues/2343
E.g.
using json schema:
`DocumentType.json`
```json
{
"$id": "datamodel",
"$schema": "https://json-schema.org/draft-07/schema#",
"$ref": "#/definitions/DocumentType",
"definitions": {
"DocumentType": {
"type": "string",
"title": "DocumentType",
"enum": ["abc", "def"]
}
}
}
```
And running the following command:
```
./script/quicktype --src-lang schema DocumentType.json -l dart --use-json-annotation
```
The output is:
```dart
// To parse this JSON data, do
//
//     final documentType = documentTypeFromJson(jsonString);
import 'package:json_annotation/json_annotation.dart';
import 'dart:convert';
part 'document_type.g.dart';
DocumentType documentTypeFromJson(String str) => …
```

Support @JsonValue for enums in Dart when using useJsonAnnotation

---

packages/quicktype-core/src/language/Dart.ts

Dart language enhancements:
* Resolves missing `@JsonKey()` for `--use-freezed` option https://github.com/quicktype/quicktype/issues/2162 https://github.com/quicktype/quicktype/issues/2339 
* Consructors generated with `--use-json-annotation` or `--use-freezed` will respect the `required` keyword even if the type is considered nullable (we forgot to check if the prop was not optional!).
* `!prop.isOptional` checks if the var has been explicitly defined as non-nullable
* Fixes `--use-freezed` option always assuming everything is nullable and appending `?` to the end of the type -- this should now be covered by the `required` check, plus the `?` was already factored in by the Dart prop type to begin with.
* Suppress comment tutorial on how to use the generated functions, when …

[Dart] Add missing output @JsonKey output for @freezed option

---

packages/quicktype-core/src/language/CJSON.ts

These changes implement the feature requests in #2347 and #2346

cJSON Additional Settings

---

packages/quicktype-core/src/language/TypeScriptEffectSchema.ts
test/fixtures/typescript-effect-schema/main.ts
test/fixtures/typescript-effect-schema/package-lock.json
test/fixtures/typescript-effect-schema/package.json

- fix type inference
- output more idiomatic @effect/schema code

fixes for latest @effect/schema version

---

.github/workflows/test-pr.yaml

fixes #2453 
I suspect that #2453 was allowed to occur because you're not typechecking

fix: typecheck prs

---

.github/workflows/test-pr.yaml

Reverts glideapps/quicktype#2454

Revert "fix: typecheck prs"

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Adds Bug Report and Feature Request templates, PR Template
Check them out here: https://github.com/inferrinizzard/quicktype/issues/new/choose
N/a

Add GH Issue and PR Templates

---

.github/workflows/test-pr.yaml

[](https://github.com/actions/runner/issues/2566#issuecomment-1523814835)

Fail the workflow if anything earlier fails

---

packages/quicktype-core/src/TypeUtils.ts

Reverts glideapps/quicktype#2600

Revert "Revert "Revert import order to fix imported class being not yet defined""

---

.github/workflows/test-pr.yaml

Disable Swift CI check due to gpg issue

---

.github/workflows/master.yaml
.github/workflows/test-pr.yaml
packages/quicktype-core/env.sh

- add PUBLISH var to publish script
- add check in quicktype-core prebuild shell script to skip if PUBLISH

Fix fetch for ci but not publish

---

packages/quicktype-core/src/RendererOptions/index.ts
packages/quicktype-core/src/RendererOptions/types.ts
src/index.ts

- Cleaned and added comments to OptionDefinition interface
- Exposed value map for EnumOptions

chore: Clean up OptionDefinition

---

src/GraphQLIntrospection.ts
src/index.ts
test/buildkite.ts
test/fixtures.ts
test/languages.ts
test/lib/deepEquals.ts
test/lib/multicore.ts
test/test.ts
test/utils.ts

chore: Lint and cleanup CLI package
