glideapps/quicktype

- src/Options.purs
I'm going to pass querystring parameters as renderer options on quicktype.io, so unknown options need to be ignored rather than cause crashes.
> Filter invalid renderer options

- src/Language/CSharp.purs
> Remove expression-bodied members from C# for C# 5 (Unity) compatibility.

- package.json
- src/Language/CSharp.purs
* `density=dense` puts `JSONProperty` and auto-properties on one line
* ~~`immutable=true` omits setters~~ Immutable properties don't deserialize
> Adds a 'density=dense' option for rendering C# properties more compactly

- src-ts/Language/CSharp.ts
- src-ts/Type.ts
If the top-level directly contained a named
type was wasn't one itself, we would make
that type the same as the top-level.  This was
incorrect in the case where the named type
was a nullable union, which we don't
actually give a name to.
Fixes #265
> Disregard nullables when naming top level

- src/index.ts
- src/quicktype.ts
- test/utils.ts
When we run quicktype from test we must throw, not exit.
Fixes #303
> Don't process.exit from quicktype unless CLI

- .travis.yml
- package.json
- script/build.ts
- script/publish.sh
Publish from root project directory rather than dist. This makes things like `npm link` work.
ci:skip-tests
> Simplify npm packaging

- src/ConvenienceRenderer.ts
- src/Language/CPlusPlus.ts
- src/Language/CSharp.ts
- src/Language/Elm.ts
- src/Language/Golang.ts
- src/Language/JSONSchema.ts
- src/Language/Java.ts
- src/Language/SimpleTypes.ts
- src/Language/Swift.ts
- src/Language/TypeScript.ts
- src/Renderer.ts
- src/TargetLanguage.ts
- src/index.ts
This does three things:
1. Add an API-only option to let the renderer emit leading comments.
2. Implement `just-types` for all renderers where it applies (it makes no sense for Simple Types and JSON Schema).
3. Not emitting packages/namespaces/whatever for `just-types`.
@dvdsgl Objections to 3?
> Extension features

- package.json
- src/ConvenienceRenderer.ts
- src/Language/Swift.ts
- test/fixtures/swift/main.swift
- test/languages.ts
https://app2.quicktype.io/#l=swift
---
> [NOMERGE] Swift improvements

- src/Language/Golang.ts
- test/languages.ts
Unfortunately we don't check the validity of
the enums anymore, both when marshalling
and when unmarshalling.  If we kept the
custom marshalling methods we could check
there, but they wouldn't get invoked in all
cases, like the integers before, so we'd have
checking in most, but not all cases, and a hard
job of explaining which case applies in which
situation.
> Use strings for Go enums. Fixes #373

- src/CombineClasses.ts
- src/InferMaps.ts
- src/JSONSchemaInput.ts
- src/Type.ts
- src/TypeBuilder.ts
- src/UnifyClasses.ts
Having them fixed prevents conversion to maps.
> Don't make unified classes fixed

- src/Type.ts
- src/TypeBuilder.ts
The debugger will invoke getters at will.
> TypeRef.index has side-effects, so it can't be a getter

- src/ConvenienceRenderer.ts
- src/Language/CPlusPlus.ts
- src/Language/Elm.ts
- src/Language/Java.ts
- src/Language/Swift.ts
With forbidden words as well as named types and functions in the global namespace, there was no way to make property names that could be the same as global names but still rename them if they clash with forbidden names.  Now we keep forbidden names and global names in separate namespaces.
> Separate namespace for forbidden words. Fixes #420

- src/Language/Objective-C.ts
* Omit function prototypes for top-level object types
* Remove fromJSON and toJSON convenience methods
> Simplify Objective-C by omitting a few extras

- src/Language/Objective-C.ts
- test/fixtures/objective-c/QTTopLevel.h
* Enables automatic marshaling of primitives, so object properties are now `BOOL`, `NSInteger`, and `double` rather than `NSNumber*` when possible.
> Use KVC for Objective-C

- package.json
- src/Language/Objective-C.ts
* Don't allow 'id' as a property name
* `NSNullable` as function (Avoids re-evaluating parameter and works on iOS)
* Properties as tidy table with types aligned
> Objective-C small changes

- src/Language/CSharp.ts
> Don't forbid type names for properties in C#

- src/Language/Rust.ts
- test/languages.ts
For `pokedex.json`:
```rust
extern crate serde_json;
#[derive(Serialize, Deserialize)]
pub struct Pokedex {
pokemon: Vec<Pokemon>,
}
#[derive(Serialize, Deserialize)]
pub struct Pokemon {
id: i64,
num: String,
name: String,
img: String,
#[serde(rename = "type")]
purple_type: Vec<String>,
height: String,
weight: String,
candy: String,
candy_count: Option<i64>,
egg: Egg,
spawn_chance: f64,
avg_spawns: f64,
spawn_time: String,
multipliers: Option<Vec<f64>>,
weaknesses: Vec<Weakness>,
next_evolution: Option<Vec<Evolution>>,
prev_evolution: Option<Vec<Evolution>>,
}
#[derive(Serialize, Deserialize)]
pub struct Evolution {
num: String,
name: String,
}
#[derive(Serialize, Deserialize)]
pub enum Egg {
#[serde(rename = "Not in Eggs")]
NotInEggs,
#[serde(rename = "Omanyte Candy")]
OmanyteCandy, …
```
> Dense option for Rust

- src/JSONSchemaInput.ts
The string format can be anything and there's no need to fail if
the format isn't recognized / interpreted.
> json-schema: Don't error on unsupported string formats.

- src/PostmanCollection.ts
For example:
```csharp
/// <summary>
/// Response Status Code
/// 
/// GET https://postman-echo.com/status/200
/// 
/// This endpoint allows one to instruct the server which status code to respond with.
/// 
/// Every response is accompanied by a status code. The status code provides a summary of the
/// nature of response sent by the server. For example, a status code of `200` means
/// everything is okay with the response and a code of `404` implies that the requested URL
/// does not exist on server.
/// A list of all valid HTTP status code can be found at the [List of Status
/// Codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) wikipedia article. When
/// using Postman, the response status code is described for easy reference.
/// 
/// Note that if an invalid status code …
```
> Include postman item names and request urls in descriptions

- src/Inference.ts
- src/index.ts
So we don't combine top-levels with each other.
> Make top-levels from inferred JSON fixed

- src/Language/Golang.ts
- test/inputs/schema/direct-union.1.json
- test/inputs/schema/direct-union.schema
In the case where you had a class type with a union property, and that
class type was the value type of a map, the union wouldn't use the
custom unmarshaller, because of complicated Go stuff:
https://github.com/golang/go/issues/23263#issuecomment-354197562
> Fix unions as properties in Go

- src/Language/Swift.ts
Help Alamofire users read top-level types from responses:
```swift
Alamofire.request("https://...pokedex.json").responsePokedex { response in
if let pokedex = response.result.value {
// We have a pokedex: Pokedex
}
}
```
> Generate Alamofire response handlers for top-levels

- src/ResolveIntersections.ts
- src/TypeBuilder.ts
- src/TypeGraph.ts
We're keeping track of whether we've lost
attributes now, so the check should be
accurate.
> Enable the type attribute checks

- src/Language/Rust.ts
- test/languages.ts
#655 
This adds an option to control visibility modifiers on generated struct fields in Rust.
I don't know if I need to edit anything elsewhere or if this is good, but it appears to work from my tests!
> Add visibility option on Rust fields

- src/ConvenienceRenderer.ts
Since `commentLineStart` had a space at the end of it, if the
line in the comment was blank, there would be a space at the end
of that blank line.
In Rust, this resulted in a bunch of lines modified by `rustfmt`,
so it would be nicer to just not generate that extra bit of
whitespace.
> Remove whitespace at end of blank doc comment lines.

- src/CombineClasses.ts
- src/InferEnums.ts
- src/ResolveIntersections.ts
- src/UnifyClasses.ts
We would often do `someSet.map(...).toArray()`.  This
produces an intermediate set, which is expensive
because it must ensure that it has no duplicate members.
The better way is to do `someSet.toArray().map(...)`.
> Clean up uses of combineTypeAttributes

- src/Language/JavaScript.ts
- src/Language/Swift.ts
- src/Language/TypeScriptFlow.ts
- src/RendererOptions.ts
- src/TargetLanguage.ts
- src/cli.ts
and get an automatic 'no-x' variant on the CLI
```bash
$ quicktype getting-started.json -l swift --alamofire --no-initializers
```
Produces:
```swift
import Foundation
import Alamofire
struct GettingStarted: Codable {
let greeting: String
let instructions: [String]
}
// MARK: - Alamofire response handlers
extension DataRequest {
fileprivate func decodableResponseSerializer<T: Decodable>() -> DataResponseSerializer<T> {
return DataResponseSerializer { _, response, data, error in
guard error == nil else { return .failure(error!) }
guard let data = data else {
return .failure(AFError.responseSerializationFailed(reason: .inputDataNil))
}
return Result { try JSONDecoder().decode(T.self, from: data) }
}
}
@discardableResult
fileprivate func responseDecodable<T: Decodable>(queue: DispatchQueue? …
```
> Boolean options are named 'x' by default

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- package-lock.json
- package.json
- script/build.ts
- script/make-pkgs.sh
- script/quicktype
- src/cli/NodeIO.ts
- src/cli/analytics.ts
- src/cli/index.ts
- src/cli/storage.ts
- src/cli/telemetry.ts
- test/run-for-all.sh
- test/test.ts
- test/utils.ts
Telemetry is off by default and controlled with:
```bash
$ quicktype --telemetry enable|disable
```
Until the user enables or disables telemetry, this header is added to files produced by the quicktype CLI:
```
Please help improve quicktype by enabling anonymous telemetry with:
$ quicktype --telemetry enable
You can also enable telemetry on any quicktype invocation:
$ quicktype https://blockchain.info/latestblock -o Block.cs --telemetry enable
This helps us improve quicktype by measuring:
* How many people use quicktype?
* What features are popular or unpopular?
* How does quicktype perform? Are there any errors?
quicktype does not collect:
* Your filenames or input data
* Any personally identifiable information (PII)
* Anything not directly related to quicktype's usage
If you don't want …
```
> CLI Telemetry

- package-lock.json
- package.json
- src/__tests__/cli/ci.test.ts
- src/cli/analytics.ts
- src/cli/ci.ts
This prevents proliferation of users in environments where ~/.quicktype is not cached
> If running on CI, create a stable userId based on the project

- src/ConvenienceRenderer.ts
- src/Language/CPlusPlus.ts
- src/Language/CSharp.ts
- src/Language/Elm.ts
- src/Language/Golang.ts
- src/Language/JSONSchema.ts
- src/Language/Java.ts
- src/Language/JavaScript.ts
- src/Language/Objective-C.ts
- src/Language/Ruby/index.ts
- src/Language/Rust.ts
- src/Language/Swift.ts
With the option of making all types in a schema top-levels ,
and the same thing with TypeScript input, the likelihood
that a type name will be illegal is quite high.
> Rename top-level types if absolutely necessary

- package.json
- script/build.ts
* `quicktype` branch represents our work ahead of upstream `master`
* `dist` contains compiled JavaScript, which is required to use this library but upstream does not want in PRs.
> Use our fork of typescript-json-schema

- src/Language/Swift.ts
Since Swift 4.1, namely
- [SE-0143](https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md)
- [SE-0185](https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md)
and the fact that model is not Hashable unless it's also Equatable, as shown directly in the protocol definition
```
public protocol Hashable : Equatable {
/// The hash value.
///
/// Hash values are not guaranteed to be equal across different executions of
/// your program. Do not save hash values to use during a future execution.
public var hashValue: Int { get }
}
```
it's enough to conform quicktype's auto-generated models only to Hashable protocol.
> hashable conformance

- src/AccessorNames.ts
- src/CombineClasses.ts
- src/ConvenienceRenderer.ts
- src/FlattenUnions.ts
- src/GatherNames.ts
- src/InferEnums.ts
- src/InferMaps.ts
- src/Language/CSharp.ts
- src/Language/JSONSchema.ts
- src/Language/Java.ts
- src/Language/JavaScript.ts
- src/Language/Objective-C.ts
- src/Language/Ruby/index.ts
- src/Language/Swift.ts
- src/ReplaceObjectType.ts
- src/ResolveIntersections.ts
- src/Type.ts
- src/TypeBuilder.ts
- src/TypeGraph.ts
- src/UnifyClasses.ts
- src/cli/index.ts
- src/index.ts
- test/languages.ts
This occurs in weird circumstances when a type that's
reconstituted refers to itself.  We take greater care not
to look at a type's children before constructing it.
> Fix a graph rewriting bug.  Fixes #713

- package.json
- src/GatherNames.ts
- src/GraphQL.ts
- src/JSONSchemaInput.ts
- src/TypeGraph.ts
- src/TypeNames.ts
- src/UnifyClasses.ts
- src/cli/index.ts
- src/index.ts
The complexity of the new algorithm should be lower, and we put a cap
on the number of names we gather for a type before we assign a random
name (20 currently).
> Make gatherNames a lot faster and hopefully better

- Dockerfile
So we don't have to constantly rebuild the docker image.
> Use a fixed Ubuntu version

- src/Language/Java.ts
Converter.java would use 'instantiateMapper' method even when there were multiple classes being converted with Converter.java. This caused a compilation error because the methods available are 'instantiate{Name}Mapper' where {Name} is a name of a generated class, and instantiateMapper is not found.
jsons contains multiple json files
`script/quicktype -o javas/* -l java jsons`
`javac ...`
> No compilation error
jsons contains a single json file
`script/quicktype -o javas/* -l java jsons`
`javac ...`
> No compliation error
> [Java] Fix bug that always uses 'instantiateMapper' in Converter.java even when there are multiple classes being converted.

- src/Language/Swift.ts
It's a compiler error to define an immutable class without an initializer (or initail values)
Fixes #827
> Always emit a default initializer for classes

- script/watch
`npm run start` doesn't work for me unless I switch the directories.
Could either @schani or @dvdsgl let me know if, with https://github.com/quicktype/quicktype/commit/23080ec8debf82cad1608deed3363cf97e05f6ff, this is the correct behavior?
> Fix watch script directory

- src/quicktype-core/language/CSharp.ts
- test/inputs/schema/enum.4.json
- test/inputs/schema/enum.schema
If we don't, we end up with the non-transformed source types, such
as "string" for enums, or "object" for unions.
> Use transformation's target types in properties

- src/quicktype-core/input/CompressedJSON.ts
This PR is meant to reduce the code in `CompressedJSON.ts` and speed things up a little bit by leveraging existing `stream-json` features:
* No logic update was attempted. Whatever the code was doing before, it is doing now, right or wrong.
* `stream-json` can pack values (keys, strings, numbers) itself, which is more efficient than doing it in the client code.
* The processing pipeline length was reduced &mdash; each stream introduces an additional latency.
One algorithm improvement can be to collect only first 64 characters of a string and ignore the rest &mdash; it looks like longer values are not used anyway, but it can be a problem if user's data contains huge strings. If it is a worthwhile improvement, I can whip up another PR.
PS: `stream-json` was not updated. The same version is …
> Better leverage of stream-json to speed things up a little.

- src/quicktype-core/TypeNames.ts
- test/inputs/schema/renaming-bug.schema
Not doing this would result in random type names where
type names were actually given.
> Make TooManyTypeNames inferred when they should be

- src/quicktype-core/Run.ts
This made Objective-C crash on the CLI when no output filename
was given.
> Don't overwrite option defaults with undefined

- src/quicktype-core/Transformers.ts
- src/quicktype-core/TypeAttributes.ts
- src/quicktype-core/TypeBuilder.ts
If the intersection of two object types is built, all
attributes that aren't present in both types are
interesected with the "any" type.  If there are names
attached to "any", that leads to stupid naming results.
Now we only give the provenance attribute to "any".
> Don't give most type attributes to the any types

- src/quicktype-core/language/JavaScript.ts
When using quicktype to generate a typescript file the file was missing a few explicit any designations.  This adds them so that the output file will pass the typescript compiler in strict mode.
> Make Output Typescript Pass Strict Mode Compilation

- src/quicktype-core/language/TypeScriptFlow.ts
This fixes a issue where the `--just-types` option was ignored for flow.
> Don't emit module exports is justTypes is true

- build/quicktype-core/package-lock.json
- build/quicktype-core/package.in.json
- build/quicktype-graphql-input/package-lock.json
- build/quicktype-graphql-input/package.in.json
- build/quicktype-typescript-input/package-lock.json
- package-lock.json
- package.json
- src/quicktype-core/Transformers.ts
- src/quicktype-core/TypeAttributes.ts
- src/quicktype-core/input/CompressedJSON.ts
- src/quicktype-core/input/JSONSchemaInput.ts
It is faster, removes a dependency that is unmaintained and license-less,
and doesnt make it harder to maintain.
See https://github.com/quicktype/collection-utils/pull/3
> Replace string-hash with a Java compatible version

- src/quicktype-core/input/JSONSchemaInput.ts
Only types of array and map items should be singularized.
> Don't singularize property type names in JSON Schema

- src/quicktype-core/language/Swift.ts
- test/inputs/json/samples/simple-object.json
- test/languages.ts
In response to #794 .
This adds two CLI options for Swift targets.
`--equatable` makes types conform to `Equatable` and `--hashable` makes types conform to `Hashable`. Having the two as separate options allows for more flexibility.
In Swift 4.1, the implementation of these protocols will (in some cases) be synthesized by the compiler.
> Option to make Swift types conform to Equatable and/or Hashable

- src/cli/NodeIO.ts
- src/quicktype-core/support/Support.ts
This isn't technically required, since the JSON RFC forbids BOMs in
JSON, but it doesn't cost us anything, and we fail with a terrible error
message if a BOM is present.
> Remove the BOM from JSON input

- src/quicktype-core/ConvenienceRenderer.ts
- src/quicktype-core/language/CPlusPlus.ts
- src/quicktype-core/language/CSharp.ts
- src/quicktype-core/language/Dart.ts
- src/quicktype-core/language/Elm.ts
- src/quicktype-core/language/Java.ts
- src/quicktype-core/language/JavaScript.ts
- src/quicktype-core/language/Kotlin.ts
- src/quicktype-core/language/Objective-C.ts
- src/quicktype-core/language/Python.ts
- src/quicktype-core/language/Swift.ts
This PR switches the type of `emitCommentLines` and the various `emitDescription` methods from `string[]` to `Sourcelike[]`.
As an example, this is useful for emitting javadoc which may rely on rendering `Sourcelike` inputs. For example:
```
this.emitDescriptionBlock(['@param ', paramName, ' foos the bar'])
```
> Support Sourcelike descriptions

- src/quicktype-core/language/Objective-C.ts
It may be worth considering making most, if not all, `private` methods `protected` so that these renderers can be easily extended.
> Make emitMark available to extending Renderers

- src/quicktype-core/TypeUtils.ts
- src/quicktype-core/language/Objective-C.ts
As an extension to https://github.com/quicktype/quicktype/pull/1078, this PR opens up various methods to make it easier to extend the Objective C renderer.
Happy to discuss whether any of these API changes don't make sense.
> Make various Objective C methods protected and exported

- src/quicktype-core/ConvenienceRenderer.ts
- src/quicktype-core/language/Dart.ts
- src/quicktype-core/language/Elm.ts
- src/quicktype-core/language/Golang.ts
- src/quicktype-core/language/JSONSchema.ts
- src/quicktype-core/language/JavaScript.ts
- src/quicktype-core/language/Objective-C.ts
- src/quicktype-core/language/Rust.ts
- src/quicktype-core/language/Swift.ts
This updates all closure-based methods from all the Renderers to use methods. This allows subclasses to extend these functions, which otherwise would not be accessible via `super`.
This PR should be squashed if merged.
> Convert Renderer closures into methods

- src/quicktype-core/language/Java.ts
For defining custom namers that generate valid Java identifiers.
My use case here is that I am generating a constant variable for each class property, and need to create a namer based on the property for each constant. For example, a class property `foo_bar` may have an associated `private static final String FOO_BAR_KEY = "hello world"`
> Export javaNameStyle

- src/quicktype-core/language/Java.ts
- src/quicktype-core/language/Swift.ts
- src/quicktype-core/support/Acronyms.ts
- src/quicktype-core/support/Strings.ts
Solution for the comment around acronyms consistently relating to https://stackoverflow.com/questions/8277355/naming-convention-for-upper-case-abbreviations
Added a new CLIoption called "acronym-style" which supports originalWord, pascal, camel and capitalize as the styling for an acronym. I've added a fallback so by default we stay with the current wordstyle. 
It's has been implemented on both swift and Java to resolve the current fixme in the JavaRender 
**Example**
--acronym-style originalWord
> Acronym style

- src/quicktype-core/ConvenienceRenderer.ts
In 59cd3db87, a method was renamed, but not in this string text.
> Fix rename of method in string text.

- src/quicktype-core/language/CPlusPlus.ts
- test/languages.ts
This pull request includes the following changes:
- do not prefix identifiers with underscore (_) as that is reserved for the implementation for names in the global namespace
- use using statements instead of typedefs (as this is now the preferred standard choice)
- introduced an option to use West const (i.e. const T) or East const (i.e. T const); the default is West const
`quicktype --const-style east-const ./sample.json -o sample.cpp`
> Cpp changes marius

- src/cli/index.ts
For example, passing `--debug` without an argument
will result in `.debug === null`, which we didn't catch.
> Report missing CLI option values

- Dockerfile
- src/quicktype-core/language/CPlusPlus.ts
- test/languages.ts
Implements #1128
Added option to CLI for C++ to not depend on boost and instead depend on C++17
Tested on a large JSON schema data set (OCA OCPP 1.6 Json Schema).
Let me know if there are any issues!
> Added option to remove boost dependency

- src/quicktype-core/language/Swift.ts
> Prepend JSON functions with `fileprivate` to avoid redeclaration errors

- src/quicktype-core/index.ts
I read the article about [customizing quicktype](http://blog.quicktype.io/customizing-quicktype/) and I found the guide really helpful. I want to be able to extend other languages but the options object was not exposed. I could hack around this but defining my own but then I'd have to keep them in sync.
This PR just makes sure that all languages with options export them through the index file so that renderers/language targets can be extended
> exposes options for all languages so that the renders can be extended

- src/quicktype-core/language/JavaScript.ts
- src/quicktype-core/language/TypeScriptFlow.ts
The current output is not Babel 7 compliant.
https://github.com/quicktype/quicktype/issues/1189
Pull the `_jsOptions.runtimeCheck` output into a helper method. This is needed to decouple the output from the actual convert functions.
Converts the `namespace` block in the TS renderer to a class and updates the convert methods to be static methods. I think I like this better than `const` actually. It's also slightly simpler because of the commas needed when defining methods on an object literal.
Below is a screen shot of a sample output:
> updates typescript renderer to have babel 7 compliant output

- src/quicktype-core/language/Dart.ts
Adds `date` and `date-time` support to Dart language.
Date is back converted to date like `"2013-04-23"` and date-time is back converted to ISO 8601 like `"2013-04-23T18:25:43.511Z"`
**source JSON**
```json
{
"createdAt": "2013-04-23T18:25:43.511Z",
"some": "2013-04-23",
"name": "j"
}
```
**Generated Dart code**
```dart
class Item {
DateTime createdAt;
DateTime some;
String name;
Item({
this.createdAt,
this.some,
this.name,
});
factory Item.fromJson(Map<String, dynamic> json) => new Item(
createdAt: DateTime.parse(json["createdAt"]),
some: DateTime.parse(json["some"]),
name: json["name"],
);
Map<String, dynamic> toJson() => {
"createdAt": createdAt.toIso8601String(),
"some": "${some.year()}-${some.month()}-${some.day()}",
"name": name,
};
}
```
> add date-time support to Dart. Closes #1177

- src/quicktype-core/language/Dart.ts
As proposed in #1204, this PR optionally moves functions into class and provides alternative names.
```json
{
"name": "Pencil"
}
```
Same result as before:
```dart
Item itemFromJson(String str) => Item.fromJson(json.decode(str));
String itemToJson(Item data) => json.encode(data.toJson());
class Item {
factory Item.fromJson(Map<String, dynamic> json) => new Item(...);
Map<String, dynamic> toJson() => {...};
}
```
```dart
class Item {
factory Item.fromRawJson(String str) => Item.fromJson(json.decode(str));
String toRawJson() => json.encode(toJson());
factory Item.fromJson(Map<String, dynamic> json) => new Item(...);
Map<String, dynamic> toJson() => {...};
}
```
```dart
class Item {
factory Item.fromJson(String str) => Item.fromMap(json.decode(str));
String toJson() => json.encode(toMap()); …
```
> [dart] optionally move functions into class and provide alternative names

- package.json
- src/quicktype-core/support/Support.ts
since the yaml parser is yaml 1.2 compatible it is also able to parse json which is a subset of yaml 1.2
> Add support for yaml based json-schema

- src/quicktype-core/language/Swift.ts
This PR aims to allow `quicktype-core` users to add custom protocol conformance to generated swift code.
- I've added the `getProtocolsArray` method which takes care of assembling an array with all protocol declarations. This new method is marked as `protected` so consumers can override it.
- The `getProtocolString` method keeps being private and now only takes care of turning `getProtocolsArray` output into some swift valid string.
- Additionally I'm passing the `type` of the "class/union" being analyzed to allow for conditional customization.
```typescript
class CustomRenderer extends SwiftRenderer {
protected getProtocolsArray(t: Type): String[] {
const protocols = super.getProtocolsArray(t);
protocols.push("CustomProtocol");
return protocols;
}
}
```
> Allow custom protocol declaration in Swift

- src/quicktype-core/Renderer.ts
- src/quicktype-core/language/Swift.ts
From the issue:
> For a project in transition from Objective-C to Swift, there are scenarios where the generated model classes (which preferably are in Swift) have to be used by new code in legacy files (which are in Objective-C). Unless the class is appended with @objcMembers and inheriting NSObject, I believe the generated class will be unavailable for use by the Objective-C side.
Resolves https://github.com/quicktype/quicktype/issues/1148
There are two main components to using Swift code in Objective-C:
1. Swift classes must inherit from NSObject.
2. Swift classes must expose classes, properties, and functions to Objective-C via `@objcMembers` or `@objc` 
While `@objcMembers` is only available in Swift 5 or greater, it was the simpler option to implement and ultimately the one I chose …
> Add the ability to generate Swift code with Objective-C compatibility

- src/quicktype-core/language/Swift.ts
This PR aims to allow `quicktype-core` users to add custom class property definitions to generated swift code, giving users the ability to add features such as default values.
I've extracted the property generation logic(only for non-dense mode) that was inside the `renderClassDefinition` method to expose it in a new protected method called `propertyLinesDefinition`.
```typescript
class CustomRenderer extends SwiftRenderer {
protected propertyLinesDefinition(name: Name, parameter: ClassProperty): Sourcelike {
// Get the code for original property definition
const originalDefinition = super.propertyLinesDefinition(name, parameter);
// Return a modified version if required
return [originalDefinition, " = ",  "Some Value"];
}
}
```
> Allow custom property definition in Swift

- src/quicktype-core/language/Swift.ts
When generating swift code without the `--just-types` option from the schema:
```json
"recipe.visit":{
"$id":"#/events/recipe.visit",
"type":"object",
"description":"When a user successfully views / visits a recipe.",
"properties":{
"event":{
"type":"string",
"const":"recipe.visit"
},
"event_time":{
"type":"string"
},
},
"required":[
"event",
"event_time"
]
}
```
The output looks like this:
```swift
public struct RecipeVisit: Codable {
public let event: String
public let eventTime: String
enum CodingKeys: String, CodingKey {
case event = "event"
case eventTime = "event_time"
}
}
```
Most of the time this is correct and works fine in swift expect when we specify the `KeyDecodingStrategy.convertFromSnakeCase` in swift's `JSONDecoder` class, which converts the incoming json to `camelCase` …
> Adds ExplicitCodingkey option to SwiftOptions

- src/quicktype-core/language/JavaScript.ts
- src/quicktype-core/language/TypeScriptFlow.ts
- src/quicktype-core/support/Converters.ts
- test/languages.ts
> Support generating converters for all objects

- src/quicktype-core/Renderer.ts
- src/quicktype-core/language/Golang.ts
When running quicktype to generate Go code from a directory of schema files the output currently dumps everything into a single `.go` file. This PR breaks each named type out into its own file. 
> [IMPROVED] Generating Go files from a directory of inputs can now output one Go file per schema object.
After having been through the gauntlet with the Swift renderer, this one came together pretty fast.
Testing manually should be as simple as:
```
quicktype . -l Golang -s schema -o .
```
None.
> Multi-file Golang Output

- package-lock.json
- package.json
- src/cli/tsconfig.json
- src/quicktype-core/attributes/URIAttributes.ts
Fixes #1246 
Removed GitHub dependency for @types/urijs.
GitHub dependencies sometimes breaks in production environments.
Additionally, the DefinitelyTyped version has removed jQuery dependencies.
> Removed GitHub dependency for @types/urijs

- src/cli/index.ts
Out-of-the-box, schema introspection wasn't working with my GraphQL server as the default HTTP method was GET, but the request was using a body with the serialized content. This doesn't align with the recommended serving (in its various forms) of a graphql api over HTTP as per: https://graphql.org/learn/serving-over-http/
I was tempted to just make this `"POST"` and not wrap in `withDefault`, but I guess some people's graphql APIs might work on a GET with a body... albeit strange.
> fix: GraphQL Introspection Query

- src/quicktype-core/language/Python.ts
now `camelCase` doesn't get transformed to `snake_case` when `--no-nice-property-names`
closes #1280
> Added option to disable python snake case transformation

- src/quicktype-core/ConvenienceRenderer.ts
- src/quicktype-core/Type.ts
- src/quicktype-core/language/Python.ts
When generating python types, optional values gets type of `Optional[T]` but you still needs to give these values during initialization:
```python
@dataclass
class Object:
a: float
b: Optional[str]
```
to initialize Object you need to call `Object(a=2, b=None)`
```python
@dataclass
class Object:
a: float
b: Optional[str] = None
```
After this is merged you can call `Object(a=2,)`
Closes #1216
> Python optional properties gets None default value

- build/quicktype-core/package-lock.json
- build/quicktype-core/package.in.json
Last time I updated the `@types/urijs`, I forgot to update the dependency for the `quicktype-core` build.
> Fixed @types/urijs for quicktype-core

- src/quicktype-core/language/Dart.ts
since Dart 2.0, the "new" keyword isn't necessary, and it is discouraged.
This PR remove from the generated code, and in this file too.
> [dart] remove all "new" keyword

- package-lock.json
- package.json
- src/quicktype-core/language/Dart.ts
Added 2 new options for Dart language.
* Required constractor parameters (adds @required annotation in the constructor) and importing ```package:meta/meta.dart```
*  Final properties. (Solving #1306)
> [Dart] add required/final props

- src/quicktype-core/language/Dart.ts
closes #1307  
```dart
class Location {
final String name;
final String address;
final double latitude;
final double longitude;
Location({
this.name,
this.address,
this.latitude,
this.longitude,
});
Location copyWith({
String name,
String address,
double latitude,
double longitude,
}) =>
Location(
name: name ?? this.name,
address: address ?? this.address,
latitude: latitude ?? this.latitude,
longitude: longitude ?? this.longitude,
);
}
```
> [Dart] add copyWith option

- src/quicktype-core/attributes/TypeNames.ts
As referenced in #1331, the tooManyNamesThreshold is set too low for real business cases and needs to be increased. 
This looks like it was set to 20 by @schani during some testing and was never set back to a reasonable value. 
This has the impact of people misreporting this behavior as a defect and is an embarrassment of this otherwise fantastic project.
> Increasing tooManyNamesThreshold to 1000 from 20.

- src/quicktype-graphql-input/index.ts
Nullable scalars are always made NON_NULLABLE in generated code. This PR fixes that.
Solves:
https://github.com/quicktype/quicktype/issues/1074
https://github.com/quicktype/quicktype/issues/1296
> GQL: Make nullable scalars optional

- .gitignore
- src/quicktype-core/language/Kotlin.ts
Summary:
Kotlinx is able to handle some pretty open-ended types by just dumping them into the JsonObject and JsonArray classes. You don't get fully static types, but it at least allows you to operate on those types without having to hand-fix the code.
Details:
I had to break out various parts of KotlinRenderer's `kotlinType` function, so that subclasses can override how to handle any-like types. I've updated the renderer to map the following:
`Any` -> `JsonObject`
`List<Any>` -> `JsonArray`
`Map<*, Any>` -> `JsonObject`
Tests:
Have verified it works for reasonable inputs on my machine. Have reached out on Slack for help in navigating the fixture system to write proper tests.
> "Any" types get converted to JsonObject and JsonArray in KotlinX

- src/quicktype-core/language/JavaScript.ts
`tsc` is throwing the following:
```
'typ' is declared but its value is never read.
```
This is not a breaking change so should fit in as a patch version bump.
> Make TS noUnusedLocals happy

- src/quicktype-core/language/Python.ts
when `pyOptions.nicePropertyNames` was set to false, Python.ts would just use
original provided names for properties, which can be invalid.
Instead, we now ensure that the names are valid, but don't force
snake_case when `pyOptions.nicePropertyNames` is set to false.
We also do the same for Enums, based on the same option.
> still ensure python valid names even without style

- src/quicktype-core/language/JavaScript.ts
The JavaScript renderer already requires `es6` (uses `const`, fat arrows), so let's use `let` and `const` to make Flow and TypeScript happier.
> No more use of `var` in JavaScript

- src/quicktype-core/language/JavaScript.ts
- src/quicktype-core/language/TypeScriptFlow.ts
- test/languages.ts
By default, JavaScript, Flow, and TypeScript will throw an error if an unexpected property is found during runtime typecheck.
> Option to ignore unknown properties during runtime typecheck

- src/quicktype-core/input/JSONSchemaInput.ts
It is an alternative approach trying to resolve the ordering issue for object properties of JSON-Schemas.  Solution is to provide a propertyOrder string array on the object type. This array will be used to determine the order of properties for resulting language bindings. Example JSON:
```JSON
{
"description": "Example for ordering properties",
"type": "object",
"properties": {
"z_prop": {
"type": "string"
},
"b_prop": {
"type": "string"
},
"a_prop": {
"type": "string"
}
},
"propertyOrder": ["z_prop", "b_prop", "c_prop"]
}
``` 
Resulting typescript:
```typescript
export interface ExampleTest {
z_prop?: string;
b_prop?: string;
a_prop?: string;
}
``` 
I would also like to add some tests but I need some support on that topic.
Perhaps we could first discuss if this is a valid approach for …
> Added possibility to specify order in JSON-Schema #336

- README.md
The current link takes you to slack sign-in page, but if it is your first time (like mine) you are doomed. I had to look for a proper invite-like link on a website, so I just want to avoid others follow my struggle.
Also fixed broken link to example.
> Change slack link in readme to invite based

- src/quicktype-core/language/Golang.ts
- test/languages.ts
Optional array can be (or should be) marked as omitempty.
ref: #1288
> Go: Support `omitempty` tag for optional arrays

- src/quicktype-graphql-input/index.ts
Nullable enums are always made NON_NULLABLE in generated code. This PR fixes that.
Solves:
#1528
> Generate correct optionality of Enums  in swift from graphql

- src/quicktype-core/language/Objective-C.ts
Quicktype object initialization dictionaries may eventually receive null values in places where the user intended to send a scalar value. This change makes that non-fatal in objective-c.
At parse-time, unexpected null values for scalar types will raise exceptions and effectively throw out entire object graphs due to the default behavior of NSObject. Specifically, passing in null (NSNull) values for a scalar key in setValue:forKey: in objective-c triggers the default implementation of setNilValueForKey:, which raises an exception. This lives on a primary initialization path for Quicktype objects. Meanwhile, if the key/value were simply not included, no exception would be thrown even though that is semantically pretty close to passing in null.
The change does the following:
1. Overrides …
> setting nil value for scalar keys should not raise an exception in obj-c

- src/quicktype-core/language/JavaScript.ts
- src/quicktype-core/language/TypeScriptFlow.ts
Added option to not `JSON.parse` and `JSON.stringify` when converting to/from JSON.
Using [PouchDB](https://pouchdb.com) which provides document updates as a JS object but I still want to use quicktype for type generation and (de)serializing dates.
> Added convert JSON option for JavaScript

- src/quicktype-core/language/CPlusPlus.ts
Currently, the C++ generator generates one else-if branch for each enum
field. This causes troubles with compilers. MSVC for example limits the
number of branches to 128.
Also, conditionally checking enum fields step-by-step is at some point
slower than looking it up in a hashmap.
This PR fixes issue #1517.
> C++: Implement support for large enums (fixes #1517)

- src/quicktype-core/language/CPlusPlus.ts
It seems that some compilers can't implicitly cast the json value. Explicitly doing that by calling get<T> fixes the problem.
I reproduced the issue with the latest IAR C++ compiler for ARM.
> C++: Improve compiler support

- src/quicktype-core/index.ts
Exports `MultiFileRenderResult` in top level. Otherwise I have to do this to get the TS interface:
```ts
import {MultiFileRenderResult} from '../node_modules/quicktype-core/dist/TargetLanguage'
```
Related: https://github.com/googleapis/google-cloudevents/issues/83
> feat: export MultiFileRenderResult

- Dockerfile
ppa:jonathonf/gcc-7.1 is not exists for now, replaced by ppa:jonathonf/gcc [bionic,trusty,xenial]
> replaced ppa:jonathonf/gcc-7.1 by ppa:jonathonf/gcc

- src/quicktype-core/language/Dart.ts
Adds feature to generate small `freezed` powered class structures
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'public_answer.freezed.dart';
part 'public_answer.g.dart';
@freezed
abstract class PublicAnswer with _$PublicAnswer {
const factory PublicAnswer({
int id,
bool isMyReview,
List<Estimate> estimates,
DateTime created,
bool isVoiceAnswer,
String correctionStatus,
Question question,
}) = _PublicAnswer;
factory PublicAnswer.fromJson(Map<String, dynamic> json) => _$PublicAnswerFromJson(json);
}
```
> feat(dart): add @freezed classes support

- README.md
Current example is broken because JSONSchemaStore is an abstract class and cannot be instantiated.
Fixes #1585.
> Fix programmatic example in README ("Calling `quicktype` from JavaScript")

- src/quicktype-core/language/Kotlin.ts
It is very restricting when creating a new variant of the Kotlin target language when the main emit functions are private and can not be overwritten any more.
> Make Kotlin base emit functions protected so it can be overwritten

- Dockerfile
A prompt for donations came up when adding the repository. This
fix should ensure that the command does not hang.
Before:
```sh
$ podman build -t quicktype .
STEP 20: RUN add-apt-repository ppa:jonathonf/gcc
Collected backports of GCC
---
Donate to GNU: https://my.fsf.org/civicrm/contribute/transact?reset=1&id=57
Donate to Debian: https://www.debian.org/donations
Donate to this PPA: https://ko-fi.com/jonathonf
More info: https://launchpad.net/~jonathonf/+archive/ubuntu/gcc
Press [ENTER] to continue or ctrl-c to cancel adding it
```
After:
```sh
$ podman build -t quicktype .
STEP 20: RUN add-apt-repository ppa:jonathonf/gcc -y
gpg: keyring `/tmp/tmpdoy6vzki/secring.gpg' created
gpg: keyring `/tmp/tmpdoy6vzki/pubring.gpg' created
gpg: requesting key F06FC659 from hkp server …
```
> fix hanging docker build

- src/quicktype-core/language/CPlusPlus.ts
Close: #1563 
```cpp
inline void to_json(json & j, const quicktype::Test & x) {
j = json::object();
j["optionalField"] = x.optional_field;
j["requiredField"] = x.required_field;
}
```
```cpp
inline void to_json(json & j, const quicktype::Test & x) {
j = json::object();
if (x.get_optional_field()) {
j["optionalField"] = x.get_optional_field();
}
j["requiredField"] = x.get_required_field();
}
```
> optional field unset not in the json with null

- build/quicktype-core/package-lock.json
- build/quicktype-core/package.in.json
`quicktype-core` depends on `lodash`
https://github.com/quicktype/quicktype/blob/4a8362bc1a7a568d1d9a27320494b372f9f086fc/src/quicktype-core/language/Dart.ts#L39 but this is no listed in the package.json
> fix(core): add missing lodash dependency to quicktype-core

- src/quicktype-core/language/Swift.ts
Looks like an artifact from a different language was used in the template. Swift doesn't use `new`
`try? newJSONDecoder()` becomes `try? JSONDecoder()`
> Remove typo in template text for Swift file

- src/quicktype-core/language/Kotlin.ts
The old code is now deprecated and it is an error to use it.
> Update Kotlin (kotlinx) usage API sample code

- src/quicktype-core/language/Kotlin.ts
According to the doc for [Kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers), for any custom serializers, we need to annotate with `with`. 
- Tested with `script/quicktype --lang kotlin --framework kotlinx --src-lang schema https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json`
- The generated data bindings will be available at: https://github.com/detekt/sarif4k
> Fix KSerializer not bound for enum in kotlinx.serialization

- src/quicktype-core/language/CSharp.ts
Change to use fully qualified names for Dictionary and List.  This avoids having to edit generated files to add "using System.Collections.Generic;" to the top of them.  Fixes #1631
> Update CSharp.ts to use fully qualified names for Dictionary and List

- src/quicktype-core/language/Java.ts
When json schema contains array of object and the option array-type=list is used for java
The generated Converter class contains compilation errors into instantiateMapper 
```
reader = mapper.readerFor(List<MyClass>.class);
writer = mapper.writerFor(List<MyClass>.class);
```
instead of
```
reader = mapper.readerFor(List.class);
writer = mapper.writerFor(List.class);
```
> fix instantiateMapper readerFor and writerFor class when type is a list

- build/quicktype-core/package-lock.json
- build/quicktype-core/package.in.json
- package-lock.json
- package.json
- src/quicktype-core/language/Kotlin.ts
This change adds the acronym style to the CLI for kotlin for the just-types framework. This follows same pattern as swift acronym style option.
> Add acronym style option for kotlin

- src/quicktype-core/language/Dart.ts
As @required is deprecated, it is changed by required for annotating required properties
> Changed @required to required

- src/quicktype-core/language/Swift.ts
> description is not a keyword in Swift

- src/quicktype-typescript-input/index.ts
Generating types from TypeScript and back into TypeScript does not behave as expected (this is admittedly a strange thing to do)
[`typescript-json-schema`](https://www.npmjs.com/package/@mark.probst/typescript-json-schema) has a setting called `noExtraProps`. 
Without it (as the code currently is in `master`), you will see the following behaviour:
```ts
// foo.ts
export type Foo = {
bar: string
}
```
- `quicktype foo.ts -o out.ts`
```ts
// out.ts
export interface Foo {
bar: string;
[property: string]: any;
}
```
This makes sense to me in that it is technically correct, typescript interfaces/types are not _exact_ and you can provide additional properties. However this does not seem to necessarily be useful or wanted behaviour.
By adding `noExtraProps: true` to the `settings` in …
> Add `noExtraProps` to typescript-input generator

- src/quicktype-core/language/JavaScript.ts
TypeScript with `noImplicitAny` enabled will error and fail to compile on the `let ref` statement because its type cannot be inferred. By explicitly declaring `let ref: any` the error goes away.
The error TypeScript outputs, for the curious:
> Variable 'ref' implicitly has type 'any' in some locations where its type cannot be determined. ts(7034)
Probably for another PR, but the `ref` variable is used before it is declared, which is technically not valid because referencing a `let` binding before it has been initialized throws in JavaScript. A `var` binding would be okay as it becomes hoisted to the top of the scope with an `undefined` value. But perhaps the better fix would be to move the statement up.
> Fix type error in TypeScript output

- src/quicktype-core/language/CSharp.ts
The missing options where relegated to the classes newtonsoftCSharpOptions and systemTextJsonCSharpOptions. Yet for both they are exactly the same at the moment. Therefore the quickest way to restore the missing options for me was to merge them back to the base options class cSharpOptions.
Two points to consider.
* check required is accepted for system.text.json, but the code for it is commented out, thus not functional. This was the case in the code I based this on. Probably there was some problem with it. I would like to look into that, but I am pushing this anyway for those who need it to use. It should still work as before for newtonsoft json. That renderer was not changed.
* I need to look into how to advertise renderer specific options. The option where still there, but quicktype …
> QuickFix for #2091 and #2097

- FAQ.md
Referring to #1340:
> It is an alternative approach trying to resolve the ordering issue for object properties of JSON-Schemas. Solution is to provide a propertyOrder string array on the object type. This array will be used to determine the order of properties for resulting language bindings. 
This was renamed `quicktypePropertyOrder` before merging in #1340.
This PR adds documentation to the FAQ.
> Document `quicktypePropertyOrder` custom JSON schema property

- packages/quicktype-core/src/language/CPlusPlus.ts
As mentioned in my issue #2166, the current implementation of Quicktype's C++ code generator throws `const char*` as an exception type, instead of standard exception classes.
While technically legal, this is generally considered bad practice.
Instead, it is better to use well-known exception types instead of `const char*`.
- This **will** break existing `catch` expressions in production code!
- This uses the standard std::runtime_error class for throwing the exception
> Quicktype C++ output now throws instances of std::runtime_error instead of const char*

- test/inputs/json/misc/76ae1.json
As discussed at https://github.com/quicktype/quicktype/issues/2197, this PR remove a duplicated entry in a test file, that makes the json file invalid.
> test: remove duplicated entry in 76ae1.json

- package-lock.json
- package.json
`quicktype` package does not have dependency of `collection-utils`, but it uses the package in `index.ts` through implicit dependency of `quicktype-core`. This causes installation failure on Yarn Berry (v2 or later).
This pull request fixes the use of undeclared dependency by adding the `collection-utils` dep explicitly.
> build(deps): Fix use of undeclared dependency

- packages/quicktype-core/src/Run.ts
There are many boolean language options that cause type checking errors:
So I add `boolean` type to value.
> Fix RendererOptions type

- packages/quicktype-core/src/language/Golang.ts
PR fixes a bug that generates files with lowercase names instead of keeping the original naming convention.
> fix(Golang): fix output file names case sensitivity (unnecessary lowercasing filename characters)

- packages/quicktype-core/src/language/Swift.ts
- test/fixtures/swift/quicktype.swift
Generate structs with `Sendable` conformance for upcoming concurrency in Swift.
> Swift: Add option sendable

- packages/quicktype-core/src/language/Swift.ts
- test/languages.ts
The `optionalEnum` flag was a great extension. Unfortunately it didn't work if the actual enum was optional.
This PR fixes that, and makes use of third party code that needs to be added to the project where the generated models are used. This is an improvement, previously each generated file had an implementation of the property wrapper
> Swift: Fix optional enums

- packages/quicktype-core/src/RendererOptions.ts
- packages/quicktype-core/src/language/Golang.ts
This PR add support for generation field tags requested in issue #2204 
example 
```bash
quicktype -l go -s schema --just-types-and-package --multi-file-output --field-tags='json,bson' -t Example --src input.json -o output.go
```
example output
```golang
package main
type Example struct {
Field1 string `json:"field1" bson:"field1"`
Field2  int   `json:"field2" bson:"field2"`          
}
```
> feat(Go): Add support for custom tags generation

- packages/quicktype-core/src/language/Golang.ts
This PR fix golang enums generation requested in issue #1205 
Fix is only enum values type positioning (whitespaces change only).
```go
package schema
type Gender string
const (
Female Gender = "female"
Male Gender = "male"
)
```
```go
package schema
type Gender string
const (
Female Gender = "female"
Male   Gender = "male"
)
```
> fix(Golang): fix enums generation

- .github/workflows/test-pr.yaml
- packages/quicktype-core/src/language/All.ts
- packages/quicktype-core/src/language/TypeScriptEffectSchema.ts
- test/fixtures.ts
- test/fixtures/typescript-effect-schema/main.ts
- test/fixtures/typescript-effect-schema/package-lock.json
- test/fixtures/typescript-effect-schema/package.json
- test/fixtures/typescript-effect-schema/tsconfig.json
- test/languages.ts
Adding support for [`@effect/schema`](https://www.npmjs.com/package/@effect/schema), which is a modern alternative to Zod with full support for decoding / encoding (Zod only does decoding).
In order to prevent `const` statements not being defined yet when referencing them for object types, I used `@effect/schema`'s lazy feature. This can be further optimized by only doing that when it's actually needed. Trying to implement that though proved very difficult, so for now this is a fully working reference implementation.
Note, that the reformatting is just reflecting the `.prettierrc` of this repo. Let me know if you want that to be disabled.
> feat: add typescript-effect-schema language

- packages/quicktype-core/src/input/JSONSchemaInput.ts
- packages/quicktype-core/src/language/TypeScriptFlow.ts
Hey everyone, I added support for `const` in JSON Schema. I created two commits, the first addresses the issue #1277 and the second improves handling of single value enums for typescript (because const is a single value enum).
If the property has the const type, I interpret it as an enum with a single value. For TypeScript, I added a new case that if an enum has only a single value, it is also created as a constant. This will also change normal enums with a single value. I don't know if this causes problems, for my use case this is okay. What do you think? If the typescript change is not accepted, I can remove it from the pull request.
Could someone please review my changes and give me feedback? Your assistance is greatly appreciated! :)
> Support for "const" in JSON Schema

- packages/quicktype-core/src/input/JSONSchemaInput.ts
This fixes generation for const values other than strings. This only reverts to the generation before #2314. I will try to solve the issue described in my comment [here](https://github.com/quicktype/quicktype/issues/2325#issuecomment-1629426141) in a future PR.
> fix: const generation for types other than string #2325

- packages/quicktype-core/src/language/Rust.ts
Add `--derive-partial-eq` option for Rust. Enables deriving PartialEq trait.
> Add derive PartialEq option for Rust

- packages/quicktype-core/src/language/TypeScriptZod.ts
- test/languages.ts
The TypeScript Zod generator currently converts strings with the `date-time` format to `zod.string()`. This modifies the generator to emit `zod.coerce.date()` instead, matching the TypeScript Flow generator.
> Add TypeScript Zod support for strings with date-time format

- packages/quicktype-core/src/language/Python.ts
> Python: Ensure default properties follows non-default properties in dataclasses

- packages/quicktype-core/src/language/Rust.ts
If there is a property in the input schema with the name `async` QuickTypes produces invalid rust because `async` is a reserved word.
> [Rust] Missing reserved keyword

- src/index.ts
I noticed that "command-line-usage" has print width of 80 by default, and it does not increase when the text would fit in the terminal window. Also, the descpition of `--lang` flag shifts layout the most, so I replaced list of languages with `LANG`, since `LANG` is already defined in synopsis. Additionally, I added `--src-lang` to synopsis
<details>
<summary>Before</summary>
```log
Synopsis
$ quicktype [--lang LANG] [--out FILE] FILE|URL ...                           
LANG ... cs|go|rs|cr|cjson|c++|objc|java|ts|js|javascript-prop-               
types|flow|swift|scala3|Smithy|kotlin|elm|schema|ruby|dart|py|pike|haskell|typescript- 
zod|typescript-effect-schema|php                                              
Description
Given JSON sample data, quicktype outputs code for working with that …
```
> fix: increase --help output width from 80 to 120

- packages/quicktype-core/src/language/TypeScriptFlow.ts
resolves #2345 
A previous PR (#2314) introduced the ability to generate const values in Typescript but didn't expose that option correctly for use through the CLI. This one-line PR exposes the option (which works a treat!)
@DanielBretzigheimer
> fix: Expose the prefer-const-values Typescript language setting via CLI

- packages/quicktype-core/src/language/Python.ts
For the variable descriptions to be correctly parsed as Python variable docstrings, they need to be place beneath the variable declarations.
Tested with 
[foo.json](https://github.com/glideapps/quicktype/files/13382029/foo.json)
> Fix Python class member comment placement

- packages/quicktype-core/src/language/Rust.ts
prevents a compilation error when a struct called Option is generated and optional fields are present in the structs.
fixes #2385
> adds option to rust keywords

- test/fixtures/csharp/test.csproj
Due to [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-restore-audit) The `jsonString` at `/test/utils.ts:237` contains error message value like following, which causes `JSON.parse(jsonString)` to throw error
```
/Users/xxxxx/proj/quicktype/test/runs/schema-csharp-390aed/test.csproj : warning NU1903: Package 'Newtonsoft.Json' 10.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr
```
Simply updating the library to newer version solved the issue for now, but in future similar issue can happen again if new security issue is found.
> CI Fix - Updated Newtonsoft.Json csharp library to 13.0.3

- packages/quicktype-core/src/language/Crystal.ts
fixes #1672 
- Removes hard-coded leading comment in Crystal language renderer
> fix: removes default leading comment in Crystal

- packages/quicktype-core/src/language/TypeScriptZod.ts
Was attempting to extend the TypeScriptZod renderer and discovered that some functions were marked as private, preventing them from being easily extended
> fix: Make private members of TypeScriptZodRenderer protected

- packages/quicktype-core/src/language/Swift.ts
`Sendable` conformance should be applied unless it's a class _and_ mutable. This fixes #2291.
> Swift: apply Sendable unless it's class and mutable

- packages/quicktype-core/src/language/Rust.ts
Adds an option `--skip-serializing-none` for Rust. With the option on, it will instruct `serde` to skip serializing the optional fields if they are empty (None).
Can reduce the size and noisiness of the json output for large structs with many optional fields.
> feat(Rust): Add option to skip serializing empty optional fields

- packages/quicktype-core/src/language/Dart.ts
When using the Dart generator in combination with `--use-freezed`, the description provided in a JSON schema is not added to each class property. The counterpart (not using "freezed") does add descriptions.
I don't believe it was an intended behaviour, just a missed feature, but let me know.
> [Dart] fix: missing description emit when freezed is used

- packages/quicktype-core/src/language/Golang.ts
Followup to https://github.com/glideapps/quicktype/pull/2449
Apologies, I was concentrating on adding the functionality to the library I needed, I didn't check how the flag was exported. Unintended screw up due to my over-reliance on the live reload functionality.
> Adding missing export of new Golang option

- packages/quicktype-core/src/language/CPlusPlus.ts
Enhance clarity and informativeness of error messages in the C++ code generator for enum type conversions. Update the default case in `to_json` function to include the specific enumeration name and the unexpected value in the error message. This aids in quicker debugging and aligns with best practices in error messaging.
> Improve Error Messaging for Enumeration Conversion

- packages/quicktype-core/src/language/TypeScriptZod.ts
Added `supportsOptionalClassProperties` to `TypeScriptZodTargetLanguage` in order to fix handling of optional properties in JSON Schema that are not listed in `required` array.
```json
{
"properties": {
"foo": { "type": "string" },           // standard string
"bar": { "type": ["string", "null"] }, // string | null union
"baz": { "type": "string" },           // string, optional
"qux": { "type": ["string", "null"] }, // string | null union, optional
},
"required": ["foo", "bar"]
}
```
```ts
export const Schema = z.object({
foo: z.string(),                               // standard string
bar: z.union(z.string(), z.null()),            // string | null union
baz: z.union(z.string(), z.null()).optional(), // string, optional
qux: z.union(z.string(), z.null()).optional(), // string | null …
```
> fix: add supportsOptionalClassProperties to TypeScriptZod target language

- packages/quicktype-core/src/ConvenienceRenderer.ts
- packages/quicktype-core/src/Renderer.ts
- packages/quicktype-core/src/Run.ts
- packages/quicktype-core/src/TargetLanguage.ts
- packages/quicktype-core/src/language/CJSON.ts
- packages/quicktype-core/src/language/CPlusPlus.ts
- packages/quicktype-core/src/language/CSharp.ts
- packages/quicktype-core/src/language/Crystal.ts
- packages/quicktype-core/src/language/Dart.ts
- packages/quicktype-core/src/language/Elm.ts
- packages/quicktype-core/src/language/Haskell.ts
- packages/quicktype-core/src/language/Java.ts
- packages/quicktype-core/src/language/JavaScript.ts
- packages/quicktype-core/src/language/JavaScriptPropTypes.ts
- packages/quicktype-core/src/language/Kotlin.ts
- packages/quicktype-core/src/language/Objective-C.ts
- packages/quicktype-core/src/language/Php.ts
- packages/quicktype-core/src/language/Pike.ts
- packages/quicktype-core/src/language/Python.ts
- packages/quicktype-core/src/language/Rust.ts
- packages/quicktype-core/src/language/Scala3.ts
- packages/quicktype-core/src/language/Smithy4s.ts
- packages/quicktype-core/src/language/Swift.ts
- packages/quicktype-core/src/language/TypeScriptEffectSchema.ts
- packages/quicktype-core/src/language/TypeScriptZod.ts
- packages/quicktype-core/src/language/ruby/index.ts
- packages/quicktype-core/src/support/Comments.ts
Fixes #2332 
Updates comment types and allows `leadingComments` to support multiple comment types, adds `emitComments` method in ConvenienceRenderer
- Added types for different styles of comments (inline, description block, custom)
- Updated leadingComments references to use new type
- Updated all leadingComments logic in all relevant languages
- Added `emitComments` method in ConvenienceRenderer to handle different comment styles
- Updated `emitCommentLines` method to take object as param instead of list args
- Added `lineEnd` param to `emitCommentLines`
- renamed `beforeLine` to `beforeComment` and `afterLine` to `afterComment`
This change is backwards-compatible for all external/standard use cases as it preserves the existing `string[]` type for `leadingComments` _but_ it will break …
> feat: Support more leading comment types

- packages/quicktype-core/src/language/TypeScriptZod.ts
By ensuring that referenced types are defined before they are referenced. Tested on a fairly large set of interconnected schemas for the [bridging API](https://fdc3.finos.org/docs/agent-bridging/spec) in the [FDC3 standard](https://fdc3.finos.org/docs/fdc3-standard).
Please let me know if there's a more idiomatic way to get to the types underlying sets, unions, intersections, arrays etc..
resolves https://github.com/glideapps/quicktype/issues/2414
@ryoid @Southclaws @dvdsgl
P.S. The TypeScript effect schema language uses the same code in its generation and probably also needs these changes - I don't have a test set-up for that one however.
> fix: Typescript zod (and effect) language uses block scoped variables before they've been declared

- packages/quicktype-core/src/language/Golang.ts
Fixing logic for Golang `omitEmpty` option. The tag should only be added when the flag is set and the field is optional. Presently, if flag is set, it will be added regardless.
> Fix omit empty

- packages/quicktype-core/src/language/CPlusPlus.ts
> C++: force include for types in vector and map

- packages/quicktype-core/src/language/Golang.ts
fixes: [#2519](https://github.com/glideapps/quicktype/issues/2519)
If a json schema only has date-time referenced as an item of an array the generated Go code will not have the import for the time package. This adds an additional case to force time package imports
Changes:
* Added additional clause for time imports
> fix: Go time import bug

- packages/quicktype-core/src/language/Golang.ts
fixes: [#2530](https://github.com/glideapps/quicktype/issues/2530)
My previous fix forced generated Go code to add time imports for []time.Time types, however, the change was missing an additional update included in this fix which will ensure that the import takes place at the top of the file (otherwise it would encounter a syntax error)
Changes:
* formatted a line
* Added additional clause for time imports
Reproduction to fix bug:
Schema:
```json
{
"type": "object",
"properties": {
"timeRange": {
"type": "array",
"items": {
"type": "string",
"format": "date-time"
}
}
}
}
```
Generated Code:
```go
// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse and unparse this JSON data, add this code to your project and do:
//
//    models, err := …
```
> fix: Bug with misplaced Go time imports

- .prettierignore
Adds a .prettierignore to prevent formatting test inputs and outputs
> chore: Add .prettierignore

- packages/quicktype-core/src/language/TypeScriptFlow.ts
- test/languages.ts
Adds a `'prefer-readonly'` option to TypeScript output.
#2280 
```ts
export interface TopLevel {
age:     number;
country: Country;
females: number;
males:   number;
total:   number;
year:    number;
}
```
```ts
export interface TopLevel {
readonly age:     number;
readonly country: Country;
readonly females: number;
readonly males:   number;
readonly total:   number;
readonly year:    number;
}
```
Added to test suite under `quickTestRendererOptions`
N/a
> Add readonly option for TypeScript Language

- packages/quicktype-core/src/language/Scala3.ts
Removes an unused Renderer class (`Scala3.ts > Smithy4sRenderer`) caused by rebase merge conflicts from #2189
The actual Renderer class for Smithy4s lives in `Smithy4s.ts` 
N/a
N/a
N/a
> chore(Smithy): Remove unused Smithy4sRenderer

- packages/quicktype-core/src/language/Python.ts
Allows for int types in `to_float` for Python output
Fixes #2533 
existing `to_float` output:
```python
def to_float(x: Any) -> float:
assert isinstance(x, float)
return x
```
new`to_float` output:
```python
def to_float(x: Any) -> float:
assert isinstance(x, (int, float))
return x
```
N/a
> fix(Python): update to_float output for Python

- package-lock.json
- packages/quicktype-typescript-input/src/index.ts
Fixes an issue with type naming for TypeScript input where the name ends up as `default` if the first type in the file is `export default`.
Replaces the `topLevelName` with the name from the corresponding ref type
Fixes #1295 
```ts
/** #TopLevel */
export default class AddressBook {
/**
* A dictionary of Contacts, indexed by unique ID
*/
contacts: { [id: string]: Contact };
}
class Contact {
firstName: string;
lastName?: string;
birthday?: Date;
title?: "Mr." | "Mrs." | "Ms." | "Prof.";
emails: string[];
phones: PhoneNumber[];
/** @TJS-type integer */
highScore: number;
}
/**
* A Contact's phone number.
*/
class PhoneNumber {
number: string;
/** An optional label (e.g. "mobile") */
label?: string;
}
```
```dart
import 'dart:convert';
class Default {
Map<String, Contact> contacts; …
```
> fix(ts-input): Replace topLevelName for TypeScript input if first type is export default

- packages/quicktype-core/src/language/CSharp.ts
- packages/quicktype-core/src/language/Elixir.ts
- packages/quicktype-core/src/language/Objective-C.ts
- packages/quicktype-core/src/language/Python.ts
- packages/quicktype-core/src/language/ruby/index.ts
- packages/quicktype-core/src/support/Strings.ts
Getting a related crash here when using `quicktype-core` in web app.
> Fix unicode-properties import

- packages/quicktype-core/src/input/io/NodeIO.ts
- Use global fetch first, fallback to cross-fetch if needed
- Addresses deprecation warnings due to unresolved issues in cross-fetch, node-fetch, and whatwg-url libraries
- Ensures compatibility with environments running node.js v21+ where punycode module is deprecated
I've been following those issues on **node-fetch** https://github.com/node-fetch/node-fetch/pull/1793
And on **cross-fetch** https://github.com/lquixada/cross-fetch/issues/177
Both seems stale, so I hope that we can fix `quicktype-core` in the meantime. I've used the solution recommended into the `cross-fetch` issue toward conditional import and using native node fetch if available.
We're using `quicktype-core` in some of our tools, one of them being a cli tool, every-time a command is ran the deprecation coming from …
> refactor: update fetch import for node v21+ compatibility

- .deepsource.toml
Removes `deepsource.toml` from repo, following pending disconnect from DeepSource integration
Since we're opting out of using DeepSource as a code analyser, we no longer need the config file
> chore: Remove DeepSource Integration

- packages/quicktype-core/src/input/io/NodeIO.ts
Related to #2573.
GH Actions CI uses a browser fetch instead of Node-based fetch so the `response.body` will return as [`WebStreams.ReadableStream`](https://developer.mozilla.org/docs/Web/API/ReadableStream) instead of [`NodeJS.ReadableStream`](https://nodejs.org/api/stream.html#class-streamreadable) from `cross-fetch`.
Only allows CI to use `cross-fetch` instead.
Resolves a types issue occurring in GH CI Pipeline
N/a
N/aa
> fix: Resolve ReadableStream types issue in test suite

- package-lock.json
- packages/quicktype-core/package.json
Removes `@types/yaml` and `@types/js-base64` as types are now included in the base packages
Resolves this warning on build:
```
Run npm ci
npm WARN deprecated @types/js-base64@3.3.1: This is a stub types definition. js-base64 provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/yaml@1.9.7: This is a stub types definition. yaml provides its own type definitions, so you do not need this installed.
```
N/a
N/a
> chore: remove unused types devDeps

- package-lock.json
- package.json
- packages/quicktype-core/package.json
- packages/quicktype-graphql-input/package.json
- packages/quicktype-typescript-input/package.json
- script/quicktype
per https://github.com/glideapps/quicktype/pull/2558, the dist file layout got changed (see #2593)
- #2593
- https://github.com/Homebrew/homebrew-core/pull/171524
Run local build.
> fix: update `dist/index.js` to `dist/src/index.js`

- package-lock.json
- package.json
- packages/quicktype-core/package.json
- packages/quicktype-graphql-input/package.json
- packages/quicktype-typescript-input/package.json
- script/quicktype
Reverts glideapps/quicktype#2594
Tests are failing
> Revert "fix: update `dist/index.js` to `dist/src/index.js`"

- package.json
- src/index.ts
- tsconfig.json
Reverts the package.json import from `import` to `require`
Removes `resolveJsonModules` from `tsconfig.json`
Fixes #2593 
By including `resolveJsonModules: true` and using `import` for the `package.json` in the `index.ts` for the cli dir, we ended up introducing an extra level into the build output as including the json import hoisted the `src` dir into `dist`.
Fixed by restoring the previous code and ignoring the lint error.
Will follow-up with a new PR to get the version text in a different manner
Old dist output:
Current output:
> fix: Restores old build output by removing package.json import

- packages/quicktype-core/src/TypeUtils.ts
Reverts glideapps/quicktype#2599
> Revert "Revert import order to fix imported class being not yet defined"

- .github/workflows/test-pr.yaml
Enables test-pr workflow for `release/**` branches
> chore(repo): Allow running test pr workflow for release branches

- packages/quicktype-core/src/language/Python/PythonRenderer.ts
- packages/quicktype-core/src/language/Python/language.ts
Adds a python option `pydantic-base-model`, which will generate classes inheriting pydantic's [BaseModel](https://docs.pydantic.dev/latest/concepts/models/). 
https://github.com/glideapps/quicktype/issues/1474
[Pydantic](https://docs.pydantic.dev/latest/) is a commonly used python module for defining schemas and dataclasses with validation. It is used in [FastApi](https://fastapi.tiangolo.com/). It is a nice alternative to the builtin `dataclasses` module.
Quicktype generates standard classes or dataclasses (3.7+) for python
With the `--pydantic-base-model` option, it generates pydantic BaseModel classes
Built and generated python from a schema, with and without `--pydantic-base-model` option. 
Without the option included `from dataclasses import dataclass` and `@dataclass`
With the …
> feat(python): add --pydantic-base-model option

- packages/quicktype-core/src/language/Elixir/ElixirRenderer.ts
This change makes the various Elixir `emit` functions `protected` instead of `private`, so that they can be overridden in customized code generators.
https://github.com/glideapps/quicktype/issues/2657
Allow these functions to be overridden in subclasses.
N/A
N/A
`FIXTURE=Elixir npm test`
N/A
> feat: expose various emit functions to subclasses

- package-lock.json
- package.json
- packages/quicktype-core/package.json
- packages/quicktype-core/src/Inference.ts
- packages/quicktype-core/src/RendererOptions/index.ts
- packages/quicktype-core/src/Run.ts
- packages/quicktype-core/src/index.ts
- packages/quicktype-core/src/input/PostmanCollection.ts
- packages/quicktype-core/src/input/io/get-stream/buffer-stream.ts
- packages/quicktype-core/src/input/io/get-stream/index.ts
- packages/quicktype-core/src/language/CJSON/CJSONRenderer.ts
- packages/quicktype-core/src/language/TypeScriptFlow/TypeScriptFlowBaseRenderer.ts
- packages/quicktype-core/src/support/Support.ts
- packages/quicktype-core/src/types.ts
- packages/quicktype-graphql-input/package.json
- packages/quicktype-typescript-input/package.json
- packages/quicktype-typescript-input/src/index.ts
- packages/quicktype-vscode/package.json
- test/fixtures.ts
- test/lib/multicore.ts
- test/utils.ts
- Updates packages to TS 5.8+
- Removes old `NoInfer` type shim
- Fixes misc `any` types
- Moves inference flags map and types to own file
- Strongly types inference flags
- Refactors CJSON `includes` array as class member instead of passed ref
> chore: Update typescript to latest version

- package-lock.json
- package.json
- packages/quicktype-core/env.sh
- packages/quicktype-core/package.json
- packages/quicktype-core/src/input/io/$fetch.ci.ts
- packages/quicktype-core/src/input/io/$fetch.ts
- packages/quicktype-core/src/input/io/NodeIO.ts
- packages/quicktype-graphql-input/package.json
- packages/quicktype-typescript-input/package.json
- packages/quicktype-vscode/package.json
Replaces the cross-fetch import for NodeIO with an imported module that is substituted as build time for CI, also adds a try catch
Follow up to #2587
Fixes #2662 
Obsoletes #2673 
```ts
// We need to use cross-fetch in CI or if fetch is not available in the global scope
// We use a dynamic import to avoid punycode deprecated dependency warning on node > 20
const fetch = process.env.CI
? require("cross-fetch").default
: ((global as any).fetch ?? require("cross-fetch").default);
```
```ts
import { fetch } from '$fetch'; // <-- replaced with '$fetch.ci' in CI env
```
> Fix fetch with build-time substitution

- package-lock.json
- packages/quicktype-core/package.json
- packages/quicktype-core/src/RendererOptions/types.ts
- src/index.ts
- extend `OptionDefinition` type from `command-line-args`
- fix positional args bug with defaultOption
- add map from `optionType` to `type`
Fixes #2753 
Tested with manual CLI runs locally, will add CLI testing to CI soon
> fix: Extend OptionDefinition from command-line-args, fix positional arg bug
